language: php
php:
  - '7.0'

before_script:
  - composer self-update && composer --version
  - composer install -n

script: phpunit

addons:
  code_climate:
    repo_token: a875dfcf8f4f08bdeec3de3a28a877dc96f3836a0b58c82416bcac90bd519eba
